#!/usr/bin/env bash
# Apply the Dance integration to lib/vscode.
#
# Mirrors what our VSCodium fork does via its src/stable/ overlay + patches/user/
# patch, but adapted for code-server's quilt-style patch flow:
#
#   1. Drop the pre-built built-in extension into vscode/extensions/dance/
#   2. Drop the renderer-side workbench contribution into
#      vscode/src/vs/workbench/contrib/dance/browser/
#   3. Patch workbench.common.main.ts so the contribution actually loads
#
# Idempotent: re-running over an already-patched tree is a no-op.

set -euo pipefail

DANCE_DIR="$(cd "$(dirname "$0")" && pwd)"
VSCODE_DIR="$(cd "$DANCE_DIR/.." && pwd)/lib/vscode"

if [[ ! -d "$VSCODE_DIR" ]]; then
  echo "[dance] $VSCODE_DIR not found — run 'git submodule update --init lib/vscode' first" >&2
  exit 1
fi

echo "[dance] copying built-in extension shell → $VSCODE_DIR/extensions/dance/"
mkdir -p "$VSCODE_DIR/extensions/dance"
cp -rT "$DANCE_DIR/extension" "$VSCODE_DIR/extensions/dance"

# We load dance ourselves in the workbench's main thread (see danceLoader.ts).
# Strip the extension manifest's main/browser entries and zero its activation events so
# the regular extension host treats the directory as "manifest-only" — its
# `contributes` (commands, keybindings, configuration) still get registered, but no
# code is loaded by the extension host.  This is the magic that gets dance off
# the slow IPC path.
echo "[dance] neutering the extension shell (kept for manifest contributes only)"
python3 - "$VSCODE_DIR/extensions/dance/package.json" <<'PYEOF'
import json, sys
p = sys.argv[1]
with open(p) as f: d = json.load(f)
# Drop main/browser/activationEvents entirely: the vscode manifest validator
# (see lib/vscode/build/lib/extensions.* and @vscode/vsce) refuses a manifest
# that declares activationEvents without main/browser, even an empty list.
# Without these keys, the extension loader treats the dir as manifest-only,
# which is exactly what we want — contributes (commands/keybindings/menus)
# still get registered, but no extension code is loaded via the host.
d.pop("main", None)
d.pop("browser", None)
d.pop("activationEvents", None)
with open(p, "w") as f: json.dump(d, f, indent=2)
print("[dance]   manifest stripped of main/browser/activationEvents (contributes-only)")
PYEOF

echo "[dance] copying workbench contribution → $VSCODE_DIR/src/vs/workbench/contrib/dance/"
mkdir -p "$VSCODE_DIR/src/vs/workbench/contrib/dance"
cp -rT "$DANCE_DIR/contrib" "$VSCODE_DIR/src/vs/workbench/contrib/dance"

# Generate danceBundle.ts (the JS bundle + manifest as string literals) so the
# workbench compile picks up dance's code as part of the workbench bundle.
echo "[dance] generating danceBundle.ts from extension/out/web-extension.js"
python3 - "$DANCE_DIR/extension/out/web-extension.js" "$DANCE_DIR/extension/package.json" "$VSCODE_DIR/src/vs/workbench/contrib/dance/browser/danceBundle.ts" <<'PYEOF'
import json, sys
bundle_path, manifest_path, out_path = sys.argv[1:4]
with open(bundle_path, encoding="utf-8") as f: bundle = f.read()
with open(manifest_path, encoding="utf-8") as f: manifest = json.load(f)
# Restore main/browser in the EMBEDDED manifest copy (so dance's own
# `vscode.extensions.getExtension('gregoire.dance').packageJSON` lookups still
# return a sensible shape).  This is independent of the on-disk manifest
# we stripped above.
manifest["main"] = "./out/extension.js"
manifest["browser"] = "./out/web-extension.js"
manifest["activationEvents"] = ["*"]
with open(out_path, "w", encoding="utf-8") as f:
    f.write("// auto-generated by dance/install-into-vscode.sh — do not edit\n")
    f.write("/* eslint-disable */\n")
    f.write("export const DANCE_BUNDLE_JS = " + json.dumps(bundle) + ";\n")
    f.write("export const DANCE_MANIFEST_JSON = " + json.dumps(json.dumps(manifest)) + ";\n")
print(f"[dance]   wrote {out_path} ({len(bundle)} bytes of bundle)")
PYEOF

WORKBENCH_MAIN="$VSCODE_DIR/src/vs/workbench/workbench.common.main.ts"
if grep -q "contrib/dance/browser/dance.contribution" "$WORKBENCH_MAIN"; then
  echo "[dance] workbench.common.main.ts already wires up the contribution — skipping"
else
  # Insert our import directly after the performance contribution import.  The
  # line-number-keyed patch breaks across vscode versions; an in-place edit
  # against a unique anchor is robust to upstream churn.
  ANCHOR="import './contrib/performance/browser/performance.contribution.js';"
  if ! grep -qF "$ANCHOR" "$WORKBENCH_MAIN"; then
    echo "[dance] anchor line not found in workbench.common.main.ts — vscode layout has changed" >&2
    exit 1
  fi
  echo "[dance] inserting workbench import after the performance contribution"
  awk -v anchor="$ANCHOR" '
    {print}
    $0 == anchor && !done {
      print ""
      print "// Dance (modal editing) core contribution"
      print "import '\''./contrib/dance/browser/dance.contribution.js'\'';"
      done = 1
    }
  ' "$WORKBENCH_MAIN" > "$WORKBENCH_MAIN.tmp" && mv "$WORKBENCH_MAIN.tmp" "$WORKBENCH_MAIN"
fi

echo "[dance] integration applied."
